FreeBSD: { enabled: no }

JACOSShield-core: {
  url: "http://127.0.0.1/packages/JACOSShield_v2_7_2_amd64-core",
  mirror_type: "http",
  signature_type: "none",
  enabled: yes
}

JACOSShield: {
  url: "http://127.0.0.1/packages/JACOSShield_v2_7_2_amd64-JACOSShield_v2_7_2",
  mirror_type: "http",
  signature_type: "none",
  enabled: yes
}
